(defun my-c-settings ()
  (define-key c-mode-map "\C-m" 'reindent-then-newline-and-indent)
  (setq show-trailing-whitespace t)
  (subword-mode 1)
  (setq tab-width 4)
  (setq c-basic-offset 4)
  (setq c-indent-level 4)
  (setq c-continued-statement-offset 4)
  (setq c-brace-offset -4)
  (setq c-argdecl-indent 0)
  (setq c-label-offset -4)
  (setq c-auto-hungry-initial-state 'none)
  (setq c-delete-function 'backward-delete-char)
  (setq c-tab-always-indent t)
  (set (make-local-variable 'ac-sources)
       (append ac-sources '(ac-source-gccsense-member) 
                          '(ac-source-gccsense-static-member)))
  (auto-complete-mode 1)
)
;; BSD-ish indentation style
(add-hook 'c-mode-hook 'my-c-settings)
(add-hook 'c-mode-common-hook
          (lambda ()
            (local-set-key (kbd "C-c g") 'ff-find-other-file) 
;            (flymake-mode)
;            (gccsense-flymake-setup)
            ))
;(add-hook 'c++-mode-hook '(lambda () (flymake-mode)))
;(add-hook 'c-mode-hook '(lambda () (flymake-mode)))
