(defun my-c-settings ()
  (define-key c-mode-map "\C-m" 'reindent-then-newline-and-indent)
  (setq show-trailing-whitespace t)
  (subword-mode 1)
  (setq tab-width 2)
  (setq c-basic-offset 2)
  (setq c-indent-level 2)
  (setq c-continued-statement-offset 4)
  (setq c-brace-offset -2)
  (setq c-argdecl-indent 0)
  (setq c-label-offset -2)
  (setq c-auto-hungry-initial-state 'none)
  (setq c-delete-function 'backward-delete-char)
  (setq c-tab-always-indent t)
  (set (make-local-variable 'ac-sources)
       (append ac-sources '(ac-source-yasnippet)
                          '(ac-source-semantic)))
  (auto-complete-mode 1)
)

;; BSD-ish indentation style
(add-hook 'c-mode-hook 'my-c-settings)
(add-hook 'c-mode-common-hook
          (lambda ()
            (local-set-key (kbd "C-c g") 'ff-find-other-file) 
            ))
