(add-to-list 'auto-mode-alist '("\\.cpp\\'" . c++-mode))
(add-to-list 'auto-mode-alist '("\\.hpp\\'" . c++-mode))

;C++ Settings.
(defun my-cpp-settings ()
  (subword-mode 1)
  (setq show-trailing-whitespace t)
  (c-set-offset 'substatement-open '0)
  (setq c++-tab-always-indent t)
  (setq c-indent-level 4)
  (setq c-basic-offset 4)
  (setq c-continued-statement-offset 4)
  (setq c++-empty-arglist-indent 4)
  (setq tab-width 4 indent-tabs-mode nil)
  (define-key c++-mode-map "\C-m" 'reindent-then-newline-and-indent)
  (define-key c++-mode-map "\C-ce" 'c-comment-edit)
  (setq c++-auto-hungry-initial-state 'none)
  (setq c++-delete-function 'backward-delete-char)
  (set (make-local-variable 'ac-sources)
       (append ac-sources '(ac-source-gccsense-member) 
                          '(ac-source-gccsense-static-member)))
  (auto-complete-mode 1)
)
(add-hook 'c++-mode-hook 'my-cpp-settings)
