(use-package diminish :ensure t
  :config
  (eval-after-load "eldoc" '(diminish 'eldoc-mode))
  (eval-after-load "paredit" '(diminish 'paredit-mode))
  (eval-after-load "tagedit" '(diminish 'tagedit-mode))
  (eval-after-load "elisp-slime-nav" '(diminish 'elisp-slime-nav-mode))
  (eval-after-load "skewer-mode" '(diminish 'skewer-mode))
  (eval-after-load "skewer-css" '(diminish 'skewer-css-mode))
  (eval-after-load "skewer-html" '(diminish 'skewer-html-mode))
  (eval-after-load "smartparens" '(diminish 'smartparens-mode))
  (eval-after-load "guide-key" '(diminish 'guide-key-mode))
  (eval-after-load "whitespace-cleanup-mode" '(diminish 'whitespace-cleanup-mode))
  (eval-after-load "subword" '(diminish 'subword-mode))
  ;; (eval-after-load "ace-isearch" '(diminish 'ace-isearch-mode))
  (eval-after-load "auto-complete" '(diminish 'auto-complete-mode))
  (eval-after-load "projectile" '(diminish 'projectile-mode))
  (eval-after-load "helm" '(diminish 'helm-mode))
  (eval-after-load "flymake" '(diminish 'flymake-mode))
  (eval-after-load "twisted-dev" '(diminish 'twisted-dev-mode))
  (eval-after-load "company" '(diminish 'company-mode))
  (eval-after-load "abbrev" '(diminish 'abbrev-mode))
  (eval-after-load "tern" '(diminish 'tern-mode))
)
